apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::730335467751:role/eksctl-my-free-eks-cluster-nodegro-NodeInstanceRole-SYrhCf23MiwJ
      username: kubernetes-admin
      groups:
        - system:masters
