{{- range $serviceName, $service := .Values.services }}
  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  labels:
    app: happyboard-deployment
spec:
  replicas: {{ $service.replicas }}
  selector:
    matchLabels:
      app: {{ $serviceName }}
  template:
    metadata:
      labels:
        app: {{ $serviceName }}
    spec:
      containers:
        - name: {{ $serviceName }}
          image: {{ $service.image }}
          imagePullPolicy: Always
          resources: 
            requests: 
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits: 
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          ports:
            - containerPort: {{ $service.containerPort }}
          command: 
            {{- toYaml $service.command | nindent 10 }}
          readinessProbe:
            httpGet:
              path: {{ $service.path }}
              port: {{ $service.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
---
{{ end -}}