name: Deploy to EKS

on:
  push:
    branches:
      - main

env:
  KUBE_NAMESPACE: "happyboard-prod"
  HELM_RELEASE_NAME: "happyboard"
  HELM_CHART_PATH: "./happyboard-deployment-helmchart"
  CLUSTER_NAME: "happyboard-cluster"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure kubectl
      - name: Configure kubectl
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Setup kubectl and authenticate to EKS
      - name: Setup kubectl
        run: |
          aws eks update-kubeconfig --name happyboard-cluster --region ap-southeast-1

      # Debug kubeconfig
      - name: Debug kubeconfig
        run: |
          cat ~/.kube/config

      # Configure AWS credentials    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::730335467751:role/eksctl-my-free-eks-cluster-nodegro-NodeInstanceRole-SYrhCf23MiwJ
          aws-region: us-west-2

      # Ensure namespace exists
      - name: Ensure namespace exists
        run: |
          kubectl get namespace $KUBE_NAMESPACE || kubectl create namespace $KUBE_NAMESPACE

      # Set kubeconfig environment variable
      - name: Set kubeconfig environment variable
        run: |
          export KUBECONFIG=~/.kube/config

      # Deploy application
      - name: Deploy using helm
        run: |
          helm upgrade --install $HELM_RELEASE_NAME $HELM_CHART_PATH --namespace $KUBE_NAMESPACE
