name: Deploy to EKS

on:
  push:
    branches:
      - main

env: 
    KUBE_NAMESPACE: "happyboard-prod"
    HELM_RELEASE_NAME: "happyboard"
    HELM_CHART_PATH: "./happyboard-deployment-helmchart"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure kubectl
      - name: Configure kubectl
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Setup kubectl and authenticate to EKS
      - name: Setup kubectl
        run: |
          aws eks update-kubeconfig --name happyboard-cluster --region ${{ secrets.AWS_REGION }}

      # Deploy application
      - name: Deploy using helm
        run: |
          helm upgrade --install $HELM_RELEASE_NAME $HELM_CHART_PATH --namespace $KUBE_NAMESPACE
